version: '3.1'

services:
  nginx:
    image: yiliao/nginx-wordpress
    restart: always
    ports:
      - 80:80
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html

  wp-fpm:
    tty: true
    stdin_open: true
    image: yiliao/wordpress-fpm
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
    environment:
      # when deploy to Azure App Service, 
      # move the enviroment varibles to Application settings 
      # in App Service and put references here      
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

      # use local redis       
      WPFPM_WP_REDIS_HOST: redis
      WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"

  redis:
    image: redis:3-alpine
    restart: always
